# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://chugly.github.io/wedding/
title: Dave and Ellie Wedding
email: davemateer@gmail.com
author: Dave Mateer
description: > # "Homepage for Chelsey Contillo and Michael Gully-Santiago
 wedding in Kingston near Lewes on 18th of August 2018
copyright: ''
credits: 'Credits: github.com/chugly/wedding'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: github
    text: Blog
    url: https://daveellie.co.uk/
  - title: instagram
    text: Photos
    url: https://www.instagram.com/explore/tags/chuglywed/
  - title: shower
    text: Airbnb
    url: https://www.airbnb.com/wishlists/204150664/join?invite_code=QNCUYPRG&inviter_id=583562
  - title: spotify
    text: Playlist
    url: https://open.spotify.com/user/126045799/playlist/1KnnWPmEOm3PiQ93mpAQuF
  - title: envelope-open-o
    text: RSVP
    url: https://goo.gl/forms/PDVQXXai2lVgKkqW2
  - title: gift
    text: Registry
    url: https://www.zola.com/registry/chugly
